apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080   # Service port inside the cluster
      targetPort: 8080   # Port of the backend container
  type: ClusterIP
