services:
  backend:
    depends_on:
      - postgresdb
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/movieapp_db  # Use service name 'postgresdb' instead of 'localhost'
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - movieapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - movieapp-network

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5433:5432"  # Expose Postgres on port 5433 (from container 5432 to host 5433)
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: movieapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Add a volume for data persistence
    networks:
      - movieapp-network  # Ensure the database is on the same network as the backend

networks:
  movieapp-network:
    driver: bridge

volumes:
  postgres_data:


